image: busybox

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
    - git log --pretty=format:"%h" | while read commit_hash; do
        git checkout $commit_hash
        mkdir -p public/$commit_hash
        cp -r tasks/* public/$commit_hash/
      done
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
