image: alpine:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - apk add git
    - |
      git log --tags --simplify-by-decoration --pretty=format:"%H" | while read COMMIT_HISTORY_SHA; do
        git checkout $COMMIT_HISTORY_SHA
        mkdir -p public/$COMMIT_HISTORY_SHA
        cp -r tasks readme.md public/$COMMIT_HISTORY_SHA
      done
    - git checkout $CI_COMMIT_SHA
  artifacts:
    paths:
      - public
  only:
    - tags
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
