image: busybox

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
    - mkdir -p public/$CI_COMMIT_SHA
    - cp -r tasks/* public/$CI_COMMIT_SHA/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
